### ISSUE TITLE
`json2cbor.c` fails to build on macOS 10.15

### ISSUE THREAD

**Issue by jrmuizel** [immunant/c2rust#675]
```shell
  tools/json2cbor/json2cbor.c:201:9: error: implicit declaration of function 'asprintf' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      if (asprintf(&metadatakey, "%s%s", item->string, meta_data_marker) < 0 || metadatakey == NULL)
```

**Comment by fw-immunant** [comment]
This looks like a duplicate of #353, which has been fixed (but not in a released version, it seems). Can you try building from git (or one of the other workarounds mentioned in discussion on #353)?

**Comment by jrmuizel** [comment]
Building from git seems to help but I run into #676
