### ISSUE TITLE
Translation of enums with newtype structs errors on varargs

### ISSUE THREAD

**Issue by brk** [immunant/c2rust#1968]
```c
#include <stdarg.h>
enum E { E_0 };
int foo(int base, ...) {
  enum E format;
  va_list args;
  va_start(args, base);
  format = va_arg(args, enum E);
  return (int) format;
}

int main() {
  return foo(0, E_0);
}
```

The above program fails to translate starting with commit 24df964f2e324ed07fc09425de5e5a8679cfd38c; Rust (`cargo 1.70.0-nightly (84b7041fd 2023-04-13)`) produces the error message

```
error[E0277]: the trait bound `E: core::ffi::sealed_trait::VaArgSafe` is not satisfied
   --> src/frag.rs:23:25
    |
23  |     format = args.arg::<E>();
    |                         ^ the trait `core::ffi::sealed_trait::VaArgSafe` is not implemented for `E`
    |
    = help: the following other types implement trait `core::ffi::sealed_trait::VaArgSafe`:
              *const T
              *mut T
              f64
              i16
              i32
              i64
              i8
              isize
            and 5 others
note: required by a bound in `VaListImpl::<'f>::arg`
   --> /home/brk/.rustup/toolchains/nightly-2023-04-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ffi/mod.rs:556:26
    |
556 |     pub unsafe fn arg<T: sealed_trait::VaArgSafe>(&mut self) -> T {
    |                          ^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `VaListImpl::<'f>::arg`
```

cc @Rua
