### PR TITLE
fix compilation error on clang/llvm 21

### PR DESCRIPTION
**Pull request by bungcip**
GCCAsmStmt::getOutputConstraint() now return `std::string` instead of `StringRef`. this change is introduced in https://github.com/llvm/llvm-project/pull/131003

### CODE REVIEW

**Review by kkysen — APPROVED** [review]

**Comment by kkysen** [comment]
Thanks!
