### ISSUE TITLE
Fatal error: 'stddef.h' file not found

### ISSUE THREAD

**Issue by djc** [immunant/c2rust#1078]
I tried to transpile [cronie](https://github.com/cronie-crond/cronie). After finally getting c2rust to compile on my Gentoo box (with llvm-17.0.6 installed) and generating `compile_commands.json` via `intercept-build`, this is the output I got:

```
enrai cronie $ ../c2rust/target/release/c2rust transpile compile_commands.json
In file included from anacron/lock.c:29:
/usr/include/stdio.h:33:10: fatal error: 'stddef.h' file not found
   33 | #include <stddef.h>
      |          ^~~~~~~~~~
1 error generated.
Error while processing /home/djc/src/cronie/anacron/lock.c.
Transpiling lock.c
warning: Missing child 93960771518624 of node AstNode { tag: TagCallExpr, children: [Some(93960771518528), Some(93960771518560), Some(93960771518592), Some(93960771518624)], loc: SrcSpan { fileid: 11, begin_line: 41, begin_column: 10, end_line: 41, end_column: 40 }, type_id: Some(93960770786800), rvalue: RValue, macro_expansions: [], macro_expansion_text: None, extras: [] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
--> /usr/include/bits/stdio.h:41:10
 [-Wclang-ast]
warning: Missing child 93960772464328 of node AstNode { tag: TagCallExpr, children: [Some(93960772464328), Some(93960772464416), Some(93960772464464), Some(93960772464496)], loc: SrcSpan { fileid: 60, begin_line: 89, begin_column: 9, end_line: 89, end_column: 44 }, type_id: Some(93960770786800), rvalue: RValue, macro_expansions: [], macro_expansion_text: None, extras: [] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
--> /home/djc/src/cronie/anacron/lock.c:89:9
 [-Wclang-ast]
warning: Missing child 93960772486248 of node AstNode { tag: TagCallExpr, children: [Some(93960772486248), Some(93960772486336), Some(93960772486384), Some(93960772486416)], loc: SrcSpan { fileid: 6
0, begin_line: 204, begin_column: 9, end_line: 204, end_column: 41 }, type_id: Some(93960770786800), rvalue: RValue, macro_expansions: [], macro_expansion_text: None, extras: [] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
--> /home/djc/src/cronie/anacron/lock.c:204:9
 [-Wclang-ast]
thread 'main' panicked at 'Type conversion not implemented for TagTypeUnknown expecting 3', c2rust-transpile/src/c_ast/conversion.rs:827:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm a little confused that the process continues after the fatal error concerning `stddef.h` (and, indeed, why clang can't find that file at this point -- I have one in `/usr/lib/clang/17/include/stddef.h`). Is there something I could do for `TagTypeUnknown expecting 3`?

**Comment by fw-immunant** [comment]
As far as I can tell, this is the problem fixed by commit f3b5623b75127e38ba685faa06ee714dc2904ffb. Make sure your version of c2rust includes that commit (which is newer than the latest release, so you'll have to build from git).

**Comment by djc** [comment]
I built from 0e732f66e63902c4f8467fac51b9cfe93d458116, which should include that change, right?

**Comment by fw-immunant** [comment]
0e732f6 does include that change. You can double-check the version you have built with `c2rust --version` and you can see where the transpiler is looking for `stddef.h` with `strace` (you'll have to remove the generated `.rs` files and run the transpiler afresh):
```
strace -f -e open,openat,openat2 $CARGO_TARGET_DIR/release/c2rust transpile compile_commands.json
```

**Comment by djc** [comment]
The version is as expected. `strace` output:

```
[pid 13068] openat(AT_FDCWD, "./stddef.h", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 13068] openat(AT_FDCWD, "/usr/local/include/stddef.h", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 13068] openat(AT_FDCWD, "/usr/include/stddef.h", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
In file included from anacron/lock.c:29:
/usr/include/stdio.h:33:10: fatal error: 'stddef.h' file not found
   33 | #include <stddef.h>
      |          ^~~~~~~~~~
```

**Comment by javierhonduco** [comment]
Hi! I am also bumped into a similar error, last few lines:

```
warning: Missing child 94384084092280 of node AstNode { tag: TagBinaryOperator, children: [Some(94384084092280), Some(94384084092320)], loc: SrcSpan { fileid: 47, begin_line: 861, begin_column: 7, end_line: 861, end_column: 7 }, type_id: Some(94384081516704), rvalue: RValue, macro_expansions: [], macro_expansion_text: Some("OPTS_ZEROED(opts, sz)"), extras: [Text("-"), Null, Null] }
Exported Clang AST was invalid. Check warnings above for unimplemented features.
--> /home/javierhonduco/src/libbpf/src/bpf.c:861:7
 [-Wclang-ast]
thread 'main' panicked at c2rust-transpile/src/c_ast/conversion.rs:827:22:
Type conversion not implemented for TagTypeUnknown expecting 3
```

Repro steps:
- Install `c2rust` via `cargo install` (`C2Rust 0.20.0`)
- Clone https://github.com/libbpf/libbpf at `374036c9f1cdfe2`
- Using bear (running `3.1.5`), generate the compilation database `bear -- make`
- Run `c2rust transpile  ~/src/libbpf/src/compile_commands.json`

**Comment by Smart-SangGe** [comment]
I'm encountering a similar error:

```plain
RUST_BACKTRACE=1 c2rust transpile compile_commands.json
warning: c2rust: Encountered unsupported BuiltinType kind 478 for type __float128
1 warning generated.
Transpiling main.c
thread 'main' panicked at /home/sangge/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/c2rust-transpile-0.20.0/src/c_ast/conversion.rs:827:22:
Type conversion not implemented for TagTypeUnknown expecting 3
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: c2rust_transpile::c_ast::conversion::ConversionContext::visit_node
   3: c2rust_transpile::c_ast::conversion::ConversionContext::new
   4: c2rust_transpile::transpile_single
   5: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   6: c2rust_transpile::transpile
   7: c2rust_transpile::main
```

This happens with even the simplest C program:

```c
#include <stdio.h>

int main() {
  printf("hello world\n");
  return 0;
}
```

My steps:
- Installed c2rust via cargo install (C2Rust 0.20.0, rustc 1.85.1)
- Generated the compilation database using bear (version 3.1.5): `bear -- gcc -o main main.c`
- Ran `c2rust transpile compile_commands.json`

**Comment by RossSmyth** [comment]
Me too, though with stdio.

**Comment by fw-immunant** [comment]
> Me too, though with stdio.

@RossSmyth Could you provide some more information about the environment where this happens? OS/distro, clang version and installation path, c2rust version, etc.?

**Comment by RossSmyth** [comment]
I am on NixOS, I used the Nix shell provided, I built c2rust after entering the shell, I used bear for compiling https://github.com/xyzzy42/tg, it then said that stdio wasn't found

**Comment by RossSmyth** [comment]
The c2rust version is the HEAD of the git repo, Clang is whatever is in the Nix shell

**Comment by RossSmyth** [comment]
It would be very nice if an actual Nix derivation could be made, but I've tried and it is non-trivial due to funny things c2rust does.

**Comment by zyxhere** [comment]
This happens when bindgen (or whoever) uses libclang to generate the headers but cc being used is gcc.
Try with `export CC=clang`, then it should work
https://github.com/rust-lang/rust-bindgen/issues/1226
https://github.com/servo/gecko-media/issues/71#issuecomment-346606660
