### ISSUE TITLE
c2rust fails to build

### ISSUE THREAD

**Issue by Srinivasa314** [immunant/c2rust#282]
c2rust build fails with error
```
/home/srinivasa314/.cargo/registry/src/github.com-1ecc6299db9ec823/c2rust-ast-exporter-0.14.0/src/AstExporter.cpp:28:10: fatal error: clang/Frontend/LangStandard.h: No such file or directory
   28 | #include "clang/Frontend/LangStandard.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
clang version 10.0.1

**Comment by thedataking** [comment]
Hi @Srinivasa314, thanks for the  heads up. 

Can you try pulling down 10.0.1 via our `build_translator.py` script. You'll need to check out this branch:

https://github.com/immunant/c2rust/tree/feature/llvm-10.0.1

and run the script like so:

    ./scripts/build_translator.py --with-llvm-version=10.0.1 --skip-signature-checks

It works on my host (Ubuntu 20.04 LTS) so this could be an issue with your setup. If you still encounter this error, please let us know more about your environment so we can try to reproduce it.

**Comment by Srinivasa314** [comment]
The build works for master branch since it supports LLVM 10. The version available in crates.io does not support it.
